apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wholesale
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3500
      targetPort: 3500
      protocol: TCP
  type: ClusterIP
