apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: wholesale
data:
  DOMAIN: "wholesale-platform.com"
  FRONTEND_ORIGIN: "https://wholesale-platform.com"
  NODE_ENV: "production"
